---
title: "Paper estimations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Paper estimations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Load library and data
```{r setup, message = FALSE, warning = FALSE}
library(RobustTSLS) 
data('nak_out_data')
```

## Paper results

### Sample without 3 states

#### Drop Alaska
```{r}
Y_mat_or <- data_nak[[1]][-1,]
W_mat_or <- data_nak[[2]][-1,]
Z <- data_nak[[3]]
start_year <- 1968
state_names <- data_nak[[4]][-1]
T <- dim(W_mat_or)[2]
T_0 <- 10
```

#### Drop Mississipi and North Dakota
```{r}
pi_unit <- W_mat_or %*% (Z-mean(Z)) / var_biased(Z)/T #calculate D_i
index_sub <- (pi_unit >= quantile(pi_unit, 0.04)) &
             (pi_unit <= quantile(pi_unit, 1)) #drop inappropriate states

robust_estimates <- robust_estimate(Y_mat_or, W_mat_or, Z,
                                    NULL, NULL,
                                    index_sub, T_0,
                                    state_names, time_column = TRUE) 
```



#### Figure 1 
```{r, fig.retina = 3, fig.height= 9, fig.width=9, out.height = "100%", out.width = "100%"}
pi_delta_scatterplot(robust_estimates)
```

#### Figure 2 
```{r, fig.retina = 3, fig.width=16, fig.height=9, out.height = "100%", out.width = "100%"}
agg_ts_plot(robust_estimates, T_0, 1968)
```

#### Figure 3 
```{r, fig.retina = 3, fig.width=9, fig.height=9, out.height = "100%", out.width = "100%"}
weights_scatterplot(robust_estimates)
```


### Import full sample
```{r}
Y_mat_or_full <- data_nak[[1]]
W_mat_or_full <- data_nak[[2]]
Z_full <- data_nak[[3]]
start_year <- 1968
state_names_full <- data_nak[[4]]
T <- dim(W_mat_or)[2]
T_0 <- 10
```


```{r}
robust_estimates_full_sample <- robust_estimate(Y_mat_or = Y_mat_or_full, W_mat_or = W_mat_or_full, 
                                    Z = Z_full,unit_covariates = NULL, time_covariates = NULL,
                                    T_0 = T_0, unit_names = state_names_full, time_column = TRUE) 
```

#### Figure 5
```{r, fig.retina = 3, fig.width=9, fig.height=9, out.height = "100%", out.width = "100%"}
pi_delta_scatterplot(robust_estimates_full_sample)
```

#### Figure 6
```{r,fig.retina = 3, fig.width=16, fig.height=9, out.height = "100%", out.width = "100%"}
agg_ts_plot(robust_estimates_full_sample, T_0, 1968)
```


#### Figure 7
```{r, fig.retina = 3, fig.width=9, fig.height=9, out.height = "100%", out.width = "100%"}
weights_scatterplot(robust_estimates_full_sample)
```


