---
title: "Paper simulations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Paper simulations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Import library and data
```{r setup, message = FALSE, warning = FALSE}
library(RobustTSLS)
data('nak_out_data')
```

```{r}
Y_mat_or <- data_nak[[1]]
W_mat_or <- data_nak[[2]]
Z <- data_nak[[3]]
```

## Simulation results

### Figure 4
```{r, fig.retina = 3, fig.height= 9, fig.width=16, out.height = "100%", out.width = "100%"}
tables <- simulations(Y_mat_or, W_mat_or, Z, 
           share_t = 1/3, share_rank = 1/3, 
           rho_agg = 0.5, rho_theta_w = 0.2, rho_theta_y = 0.3, 
           B = 1000, S = 300, 
           test = TRUE, return_table = TRUE,
           K = 300, deg = 4, draw_plot = TRUE,
           height = 9 * 0.75, width = 16 * 0.75, 
           plot_folder = NULL, save_pdf = FALSE, save_sim = FALSE,
           sim_folder = NULL, sim_name = 'simulation_result', 
           seed = 1234)
```
### Table 1
```{r}
tables$performance_table
```
### Table 2
```{r}
tables$coverage_table
```


```{r}
table_alternative <- simulations(Y_mat_or, W_mat_or, Z, 
           share_t = 1/3, share_rank = 1, 
           no_noise = TRUE, rho_agg = 0.5, 
           rho_theta_w = 0.2, rho_theta_y = 0.3, 
           B = 1000, S = 300, 
           test =  FALSE, return_table = TRUE,
           K = 300, deg = 4, draw_plot = FALSE,
           height = 9 * 0.75, width = 16 * 0.75, 
           plot_folder = NULL, save_pdf = FALSE, save_sim = FALSE,
           sim_folder = NULL, sim_name = 'simulation_result', 
           seed = 1234)
```



```{r}
table_alternative$performance_table
```



